=== tokesim/tokesim/tokesim/config/config_schema.json
{
  "$id": "tokesim-model-config-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A tokesim model configuration schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "chain_type": {
     "$ref": "#/definitions/ChainType" 
    },
    "contract_config" : {
       "$ref": "#/definitions/ContractConfig"   
    },
    "model": {
      "$ref": "#/definitions/ModelConfig"
    },
    "accounts_path" : {
      "type": "string"
    },
    "$schema": {
      "type":"string"
    }
  },
  "required": [
    "version",
    "chain_type",
    "contract_config",
    "model"
  ],
  "additionalProperties": false,
  "definitions": {
    "ChainType": {
        "type":"string",
        "pattern": "^ethereum$"
    },
    "ModelParams": {
      "type":"object"
    },
    "ModelConfig": {
      "type":"object",
      "properties": {
        "package": {
          "$ref": "#/definitions/ModelModuleConfig"
        },
        "params":{
          "$ref" : "#/definitions/ModelParams"
        },
        "config": {
          "$ref" : "#/definitions/ModelModuleConfig"
        },
        "dashboard": {
          "$ref": "#/definitions/ModelModuleConfig"
        }
      }
    },
    "ModelModuleConfig": {
      "type":"object",
      "properties": {
        "module_name": {
          "type":"string"
        },
        "module_path": {
          "type":"string"
        },
        "class_name": {
          "type":"string"
        }
      }
    },
    "ContractConfig": {
      "oneOf": [
        {
          "$ref": "#/definitions/EthereumContractConfig"
        }
      ]      
    },
    "EthereumContractConfig": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "abi_path": {
            "type": "string"
          },
          "bytecode_path": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }        
        }
      }
    }
  }
}

=== tokesim/tokesim/tests/fixtures/config/test-simulation-config.json
{
  "$schema": "../../../tokesim/config/config_schema.json",
  "chain_type": "ethereum",
  "contract_config": [
    {
      "name": "TestToken",
      "abi_path": "./tests/fixtures/contracts/TestToken_abi.json",
      "bytecode_path": "./tests/fixtures/contracts/TestToken.bin"
    }
  ],
  "accounts_path": "./tests/fixtures/config/accounts.json",
  "model": {
    "package": {
      "class_name": "DummyModel",
      "module_name": "tests.fixtures.dummy_simulation",
      "module_path": "."
    },
    "dashboard": {
      "class_name": "DummyDashboard",
      "module_name": "tests.fixtures.dummy_dashboard",
      "module_path": "."

    },
    "config": {
      "class_name": "DummyTokenConfig",
      "module_name": "tests.fixtures.dummy_token_config",
      "module_path": "."
    },
    "params": {
      "number": 1,
      "string": "two"
    }
  },
  "version": "version-1"
}
